### ISSUE TITLE
String at the end of is not found

### ISSUE THREAD

**Issue by derula** [RyogaMasaki/jstrings#4]
It seems like a string is not considered valid unless there are at least 3 bytes following it before EOF.

[good.txt](https://github.com/drojaazu/jstrings/files/9155014/good.txt): jstrings finds the Haiku
[bad.txt](https://github.com/drojaazu/jstrings/files/9155015/bad.txt): jstrings does not find the Haiku

I'm not sure if this is expected behavior or a bug, I just noticed it while testing and thought I might as well report it.

**Comment by drojaazu** [comment]
This was due to reaching the end of the file before the end of the string was detected. This should be fixed in v1.6.
